
import __ASTRO_IMAGE_IMPORT_Z1Xz8gw from "/src/images/influences/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fjordan-wells.md";
import __ASTRO_IMAGE_IMPORT_Z1Sc5xW from "/src/images/influences/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fdavid-lee.md";
import __ASTRO_IMAGE_IMPORT_Z1wYNzW from "/src/images/influences/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fisaac-turner.md";
import __ASTRO_IMAGE_IMPORT_Z1i9ihl from "/src/images/influences/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Femma-carter.md";
import __ASTRO_IMAGE_IMPORT_pT4TS from "/src/images/projects/caf.png?astroContentImageFlag=&importer=src%2Fcontent%2Flexicon%2F3.md";
import __ASTRO_IMAGE_IMPORT_1O8nsw from "/src/images/projects/oxbow.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdomains%2F2.md";
import __ASTRO_IMAGE_IMPORT_1DfUsv from "/src/images/influences/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fjuliet-ramos.md";
import __ASTRO_IMAGE_IMPORT_2031g3 from "/src/images/customers/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2vdlfx from "/src/images/customers/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md";
import __ASTRO_IMAGE_IMPORT_1q7eWH from "/src/images/customers/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md";
import __ASTRO_IMAGE_IMPORT_hfGm1 from "/src/images/customers/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md";
import __ASTRO_IMAGE_IMPORT_QbsEm from "/src/images/customers/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md";
import __ASTRO_IMAGE_IMPORT_ZQAQeF from "/src/images/customers/7.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F7.md";
import __ASTRO_IMAGE_IMPORT_ZhF4Vk from "/src/images/customers/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md";
import __ASTRO_IMAGE_IMPORT_Z1qwCx1 from "/src/images/customers/8.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F8.md";
import __ASTRO_IMAGE_IMPORT_2ljtRH from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_ZCcPMS from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_1trWks from "/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_BApMd from "/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z1u4nl8 from "/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z2lUTSn from "/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_Zl02Tr from "/src/images/projects/perceptiosphere.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2FBibliotheca-Futurae.md";
export default new Map([["/src/images/influences/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fjordan-wells.md", __ASTRO_IMAGE_IMPORT_Z1Xz8gw], ["/src/images/influences/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fdavid-lee.md", __ASTRO_IMAGE_IMPORT_Z1Sc5xW], ["/src/images/influences/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fisaac-turner.md", __ASTRO_IMAGE_IMPORT_Z1wYNzW], ["/src/images/influences/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Femma-carter.md", __ASTRO_IMAGE_IMPORT_Z1i9ihl], ["/src/images/projects/caf.png?astroContentImageFlag=&importer=src%2Fcontent%2Flexicon%2F3.md", __ASTRO_IMAGE_IMPORT_pT4TS], ["/src/images/projects/oxbow.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdomains%2F2.md", __ASTRO_IMAGE_IMPORT_1O8nsw], ["/src/images/influences/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Finfluences%2Fjuliet-ramos.md", __ASTRO_IMAGE_IMPORT_1DfUsv], ["/src/images/customers/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md", __ASTRO_IMAGE_IMPORT_2031g3], ["/src/images/customers/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md", __ASTRO_IMAGE_IMPORT_Z2vdlfx], ["/src/images/customers/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md", __ASTRO_IMAGE_IMPORT_1q7eWH], ["/src/images/customers/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md", __ASTRO_IMAGE_IMPORT_hfGm1], ["/src/images/customers/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md", __ASTRO_IMAGE_IMPORT_QbsEm], ["/src/images/customers/7.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F7.md", __ASTRO_IMAGE_IMPORT_ZQAQeF], ["/src/images/customers/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md", __ASTRO_IMAGE_IMPORT_ZhF4Vk], ["/src/images/customers/8.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F8.md", __ASTRO_IMAGE_IMPORT_Z1qwCx1], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_2ljtRH], ["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_ZCcPMS], ["/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_1trWks], ["/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_BApMd], ["/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_Z1u4nl8], ["/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z2lUTSn], ["/src/images/projects/perceptiosphere.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2FBibliotheca-Futurae.md", __ASTRO_IMAGE_IMPORT_Zl02Tr]]);
		