/**
 * robots.txt for crawlers. References the sitemap generated by @astrojs/sitemap.
 */
const site = import.meta.env.SITE ?? "https://findcongwang.com";

export function GET() {
  const body = `User-agent: *
Allow: /

Sitemap: ${site}/sitemap-index.xml`;
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
}
